// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/agreements": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agreements"
                ],
                "summary": "Get all agreements",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Agreement"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agreements"
                ],
                "summary": "Create a rental agreement",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/assets": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assets"
                ],
                "summary": "Get all assets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Asset"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assets"
                ],
                "summary": "Create an asset",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/signin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Sign in a user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/signup": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Sign up a new user",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/contracts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Get all contracts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Contract"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Create a contract",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/contracts/amc": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Get all AMC contracts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Contract"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/contracts/lease": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Get all lease contracts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Contract"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/dashboard/active-rental-count": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get total active rental count",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/dashboard/total-amc-contracts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get total AMC contract count",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/dashboard/total-assets": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get total asset count",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/dashboard/total-properties": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get total property count",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/form/country": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Form"
                ],
                "summary": "Get all countries",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/form/district/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Form"
                ],
                "summary": "Get districts by state ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "State ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/form/state/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Form"
                ],
                "summary": "Get states by country ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Country ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/form/taluk/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Form"
                ],
                "summary": "Get taluks by district ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "District ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/properties": {
            "get": {
                "description": "Retrieve all properties with complete details including address, land details, tax details, media, and ownership information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Properties"
                ],
                "summary": "Get all properties",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Property"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/properties/agricultural": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Properties"
                ],
                "summary": "List agricultural land properties",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Property"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/properties/basic": {
            "post": {
                "description": "Creates property with all text fields. Use UploadPropertyFiles endpoint to upload binary files after.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Properties"
                ],
                "summary": "Add a new property with text information only (Step 1)",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/properties/commercial": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Properties"
                ],
                "summary": "List commercial land properties",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Property"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/properties/residential": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Properties"
                ],
                "summary": "List residential land properties",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Property"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/properties/{id}/files": {
            "post": {
                "description": "Upload ScannedDeed and Receipt files to S3 for an existing property",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Properties"
                ],
                "summary": "Upload binary files for a property (Step 2)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Property ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Scanned Deed PDF/Image",
                        "name": "scanned_deed",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Tax Receipt PDF/Image",
                        "name": "receipt",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Address": {
            "type": "object",
            "properties": {
                "address_id": {
                    "type": "integer"
                },
                "hobli": {
                    "type": "string"
                },
                "lat_coordinate": {
                    "type": "string"
                },
                "long_coordinate": {
                    "type": "string"
                },
                "pincode": {
                    "type": "string"
                },
                "street_address": {
                    "type": "string"
                },
                "taluk": {
                    "$ref": "#/definitions/models.TalukMaster"
                },
                "taluk_id": {
                    "type": "integer"
                },
                "village": {
                    "type": "string"
                }
            }
        },
        "models.Agreement": {
            "type": "object",
            "properties": {
                "agreement_id": {
                    "type": "integer"
                },
                "contact_no": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deposit": {
                    "type": "number"
                },
                "end_date": {
                    "type": "string"
                },
                "property": {
                    "description": "relation",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Property"
                        }
                    ]
                },
                "property_id": {
                    "type": "integer"
                },
                "rent": {
                    "type": "number"
                },
                "start_date": {
                    "type": "string"
                },
                "tenant_name": {
                    "type": "string"
                }
            }
        },
        "models.Asset": {
            "type": "object",
            "properties": {
                "asset_amc_provider": {
                    "type": "string"
                },
                "asset_cost": {
                    "type": "string"
                },
                "asset_end_date": {
                    "type": "string"
                },
                "asset_id": {
                    "type": "integer"
                },
                "asset_location": {
                    "type": "string"
                },
                "asset_name": {
                    "type": "string"
                },
                "asset_start_date": {
                    "type": "string"
                },
                "asset_type": {
                    "$ref": "#/definitions/models.AssetTypeMaster"
                },
                "asset_type_id": {
                    "description": "foreign key → asset_type_master",
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "property": {
                    "description": "relations",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Property"
                        }
                    ]
                },
                "property_id": {
                    "description": "foreign key → property",
                    "type": "integer"
                }
            }
        },
        "models.AssetTypeMaster": {
            "type": "object",
            "properties": {
                "asset_type_id": {
                    "type": "integer"
                },
                "asset_type_name": {
                    "type": "string"
                }
            }
        },
        "models.Contract": {
            "type": "object",
            "properties": {
                "asset": {
                    "description": "relations",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Asset"
                        }
                    ]
                },
                "asset_id": {
                    "description": "foreign key → assets",
                    "type": "integer"
                },
                "contract_id": {
                    "type": "integer"
                },
                "contract_type": {
                    "$ref": "#/definitions/models.ContractTypeMaster"
                },
                "contract_type_id": {
                    "description": "foreign key → contract_type_master",
                    "type": "integer"
                },
                "cost": {
                    "type": "number"
                },
                "end_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "related_to": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "terms": {
                    "type": "string"
                }
            }
        },
        "models.ContractTypeMaster": {
            "type": "object",
            "properties": {
                "contract_type_id": {
                    "type": "integer"
                },
                "contract_type_name": {
                    "type": "string"
                }
            }
        },
        "models.CountryMaster": {
            "type": "object",
            "properties": {
                "country_id": {
                    "type": "integer"
                },
                "country_name": {
                    "type": "string"
                }
            }
        },
        "models.DistrictMaster": {
            "type": "object",
            "properties": {
                "district_id": {
                    "type": "integer"
                },
                "district_name": {
                    "type": "string"
                },
                "state": {
                    "$ref": "#/definitions/models.StateMaster"
                },
                "state_id": {
                    "type": "integer"
                }
            }
        },
        "models.Property": {
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/models.Address"
                },
                "address_id": {
                    "type": "integer"
                },
                "buildingDetails": {
                    "$ref": "#/definitions/models.PropertyBuildingDetails"
                },
                "created_at": {
                    "type": "string"
                },
                "income": {
                    "type": "string"
                },
                "landDetails": {
                    "$ref": "#/definitions/models.PropertyLandDetails"
                },
                "media": {
                    "$ref": "#/definitions/models.PropertyMedia"
                },
                "original_deed": {
                    "type": "string"
                },
                "ownership": {
                    "$ref": "#/definitions/models.PropertyOwnershipDetails"
                },
                "propertyType": {
                    "$ref": "#/definitions/models.PropertyTypeMaster"
                },
                "property_id": {
                    "type": "integer"
                },
                "property_name": {
                    "type": "string"
                },
                "property_type_id": {
                    "type": "integer"
                },
                "taxDetails": {
                    "$ref": "#/definitions/models.PropertyTaxDetails"
                },
                "user_id": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "models.PropertyBuildingDetails": {
            "type": "object",
            "properties": {
                "application_no": {
                    "type": "string"
                },
                "building_details_id": {
                    "type": "integer"
                },
                "built_up_area": {
                    "type": "string"
                },
                "plot_size": {
                    "type": "string"
                },
                "property": {
                    "$ref": "#/definitions/models.Property"
                },
                "property_id": {
                    "type": "integer"
                },
                "year_of_construction": {
                    "type": "string"
                }
            }
        },
        "models.PropertyLandDetails": {
            "type": "object",
            "properties": {
                "acre": {
                    "type": "string"
                },
                "converted": {
                    "type": "string"
                },
                "ec": {
                    "type": "string"
                },
                "gunte": {
                    "type": "string"
                },
                "karab": {
                    "type": "string"
                },
                "khata_no": {
                    "type": "string"
                },
                "khuskitari": {
                    "type": "string"
                },
                "land_details_id": {
                    "type": "integer"
                },
                "mr_no": {
                    "type": "string"
                },
                "property": {
                    "$ref": "#/definitions/models.Property"
                },
                "property_id": {
                    "type": "integer"
                },
                "purpose": {
                    "type": "string"
                },
                "rtc": {
                    "type": "string"
                },
                "sy_no": {
                    "type": "string"
                }
            }
        },
        "models.PropertyMedia": {
            "type": "object",
            "properties": {
                "media_id": {
                    "type": "integer"
                },
                "photo_link": {
                    "type": "string"
                },
                "property": {
                    "$ref": "#/definitions/models.Property"
                },
                "property_id": {
                    "type": "integer"
                },
                "remarks": {
                    "type": "string"
                },
                "scanned_deed_url": {
                    "type": "string"
                }
            }
        },
        "models.PropertyOwnershipDetails": {
            "type": "object",
            "properties": {
                "acquisition_type": {
                    "type": "string"
                },
                "incharge": {
                    "type": "string"
                },
                "ownership_id": {
                    "type": "integer"
                },
                "phone_number": {
                    "type": "string"
                },
                "property": {
                    "$ref": "#/definitions/models.Property"
                },
                "property_id": {
                    "type": "integer"
                },
                "received_from": {
                    "type": "string"
                },
                "registration_details": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.PropertyTaxDetails": {
            "type": "object",
            "properties": {
                "property": {
                    "$ref": "#/definitions/models.Property"
                },
                "property_id": {
                    "type": "integer"
                },
                "receipt_no": {
                    "type": "string"
                },
                "receipt_url": {
                    "type": "string"
                },
                "tax_amount_paid_current_year": {
                    "type": "number"
                },
                "tax_amount_paid_previous_year": {
                    "type": "number"
                },
                "tax_id": {
                    "type": "integer"
                },
                "tax_paid": {
                    "type": "boolean"
                }
            }
        },
        "models.PropertyTypeMaster": {
            "type": "object",
            "properties": {
                "property_type_id": {
                    "type": "integer"
                },
                "property_type_name": {
                    "type": "string"
                }
            }
        },
        "models.StateMaster": {
            "type": "object",
            "properties": {
                "country": {
                    "$ref": "#/definitions/models.CountryMaster"
                },
                "country_id": {
                    "type": "integer"
                },
                "state_id": {
                    "type": "integer"
                },
                "state_name": {
                    "type": "string"
                }
            }
        },
        "models.TalukMaster": {
            "type": "object",
            "properties": {
                "district": {
                    "$ref": "#/definitions/models.DistrictMaster"
                },
                "district_id": {
                    "type": "integer"
                },
                "taluk_id": {
                    "type": "integer"
                },
                "taluk_name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
