// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/agreements": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agreements"
                ],
                "summary": "Get all agreements",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Agreement"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agreements"
                ],
                "summary": "Create a rental agreement",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/assets": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assets"
                ],
                "summary": "Get all assets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Asset"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assets"
                ],
                "summary": "Create an asset",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/signin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Sign in a user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/signup": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Sign up a new user",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/contracts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Get all contracts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Contract"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Create a contract",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/contracts/amc": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Get all AMC contracts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Contract"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/contracts/lease": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contracts"
                ],
                "summary": "Get all lease contracts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Contract"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/properties": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Properties"
                ],
                "summary": "Add a new property",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/properties/active-rental/count": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Properties"
                ],
                "summary": "Get active rental properties count",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/properties/agricultural": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Properties"
                ],
                "summary": "List agricultural land properties",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Property"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/properties/commercial": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Properties"
                ],
                "summary": "List commercial land properties",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Property"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/properties/residential": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Properties"
                ],
                "summary": "List residential land properties",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Property"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/properties/total": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Properties"
                ],
                "summary": "Get total properties count",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Address": {
            "type": "object",
            "properties": {
                "address_id": {
                    "type": "integer"
                },
                "hobli": {
                    "type": "string"
                },
                "lat_coordinate": {
                    "type": "string"
                },
                "long_coordinate": {
                    "type": "string"
                },
                "pincode": {
                    "type": "string"
                },
                "street_address": {
                    "type": "string"
                },
                "taluk": {
                    "$ref": "#/definitions/models.TalukMaster"
                },
                "taluk_id": {
                    "type": "integer"
                },
                "village": {
                    "type": "string"
                }
            }
        },
        "models.Agreement": {
            "type": "object",
            "properties": {
                "agreement_id": {
                    "type": "integer"
                },
                "contact_no": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deposit": {
                    "type": "number"
                },
                "end_date": {
                    "type": "string"
                },
                "property": {
                    "description": "relation",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Property"
                        }
                    ]
                },
                "property_id": {
                    "type": "integer"
                },
                "rent": {
                    "type": "number"
                },
                "start_date": {
                    "type": "string"
                },
                "tenant_name": {
                    "type": "string"
                }
            }
        },
        "models.Asset": {
            "type": "object",
            "properties": {
                "amc_provider": {
                    "type": "string"
                },
                "asset_id": {
                    "type": "integer"
                },
                "asset_name": {
                    "type": "string"
                },
                "asset_type": {
                    "$ref": "#/definitions/models.AssetTypeMaster"
                },
                "asset_type_id": {
                    "description": "foreign key → asset_type_master",
                    "type": "integer"
                },
                "cost": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "property": {
                    "description": "relations",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Property"
                        }
                    ]
                },
                "property_id": {
                    "description": "foreign key → property",
                    "type": "integer"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "models.AssetTypeMaster": {
            "type": "object",
            "properties": {
                "asset_type_id": {
                    "type": "integer"
                },
                "asset_type_name": {
                    "type": "string"
                }
            }
        },
        "models.Contract": {
            "type": "object",
            "properties": {
                "asset": {
                    "description": "relations",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Asset"
                        }
                    ]
                },
                "asset_id": {
                    "description": "foreign key → assets",
                    "type": "integer"
                },
                "contract_id": {
                    "type": "integer"
                },
                "contract_type": {
                    "$ref": "#/definitions/models.ContractTypeMaster"
                },
                "contract_type_id": {
                    "description": "foreign key → contract_type_master",
                    "type": "integer"
                },
                "cost": {
                    "type": "number"
                },
                "end_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "related_to": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "terms": {
                    "type": "string"
                }
            }
        },
        "models.ContractTypeMaster": {
            "type": "object",
            "properties": {
                "contract_type_id": {
                    "type": "integer"
                },
                "contract_type_name": {
                    "type": "string"
                }
            }
        },
        "models.CountryMaster": {
            "type": "object",
            "properties": {
                "country_id": {
                    "type": "integer"
                },
                "country_name": {
                    "type": "string"
                }
            }
        },
        "models.DistrictMaster": {
            "type": "object",
            "properties": {
                "district_id": {
                    "type": "integer"
                },
                "district_name": {
                    "type": "string"
                },
                "state": {
                    "$ref": "#/definitions/models.StateMaster"
                },
                "state_id": {
                    "type": "integer"
                }
            }
        },
        "models.Property": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "relations (FKs live ONLY here — correct direction)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Address"
                        }
                    ]
                },
                "address_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "income": {
                    "type": "string"
                },
                "original_deed": {
                    "type": "string"
                },
                "property_id": {
                    "type": "integer"
                },
                "property_name": {
                    "type": "string"
                },
                "property_type": {
                    "$ref": "#/definitions/models.PropertyTypeMaster"
                },
                "property_type_id": {
                    "type": "integer"
                },
                "purpose": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                },
                "user_id": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "models.PropertyTypeMaster": {
            "type": "object",
            "properties": {
                "property_type_id": {
                    "type": "integer"
                },
                "property_type_name": {
                    "type": "string"
                }
            }
        },
        "models.RolesMaster": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string"
                },
                "roles_master_id": {
                    "type": "integer"
                }
            }
        },
        "models.StateMaster": {
            "type": "object",
            "properties": {
                "country": {
                    "$ref": "#/definitions/models.CountryMaster"
                },
                "country_id": {
                    "type": "integer"
                },
                "state_id": {
                    "type": "integer"
                },
                "state_name": {
                    "type": "string"
                }
            }
        },
        "models.TalukMaster": {
            "type": "object",
            "properties": {
                "district": {
                    "$ref": "#/definitions/models.DistrictMaster"
                },
                "district_id": {
                    "type": "integer"
                },
                "taluk_id": {
                    "type": "integer"
                },
                "taluk_name": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/models.RolesMaster"
                },
                "role_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
